### PR TITLE
Support for multiple lines

### PR DESCRIPTION
**Pull request by Urriel**
Hi 👋

I am trying to add support for multiple bars in the same row that will overlap in time but be displayed on top of each other.

### CODE REVIEW

**Comment by Urriel** [comment]
I don't think I am getting on the right path here.
Do you have any idea on how I should implement this ?

**Comment by zunnzunn** [comment]
The desired behavior ought to be specified a bit more precisely here. So each bar in a row should be rendered in its own "sub-row"?

**Comment by Urriel** [comment]
image

I want to display these bars on top of each other instead of having them overlapped.

**Comment by HelloDavideDeSimone** [comment]
Hi, Do you have any updates on this?

**Comment by Urriel** [comment]
I found a new way of doing things, I actually create a new row for the bars.

**Pull request closed without merging**
